openapi: 3.0.2
info:
  title: FastAPI
  version: 0.1.0
servers:
  - url: http://localhost:8080
paths:
  /:
    get:
      summary: Root
      operationId: root__get
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema: {}
  /user/create:
    post:
      summary: User Create
      description: 新規ユーザー作成
      operationId: user_create_user_create_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCreateRequest"
        required: true
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserCreateResponse"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
  /user/me:
    get:
      summary: User Me
      operationId: user_me_user_me_get
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SafeUser"
      security:
        - HTTPBearer: []
  /user/update:
    post:
      summary: Update
      description: Update user attributes
      operationId: update_user_update_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCreateRequest"
        required: true
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
      security:
        - HTTPBearer: []
  /room/create:
    post:
      summary: Create
      description: ルーム作成リクエスト
      operationId: create_room_create_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateRoomRequest"
        required: true
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RoomID"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
      security:
        - HTTPBearer: []
  /room/list:
    post:
      summary: Fetch List
      description: 現在入場可能なルーム取得リクエスト
      operationId: fetch_list_room_list_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RoomListRequest"
        required: true
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RoomListResponse"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
  /room/join:
    post:
      summary: Join
      description: ルーム入場リクエスト
      operationId: join_room_join_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RoomJoinRequest"
        required: true
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RoomJoinResponse"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
      security:
        - HTTPBearer: []
  /room/wait:
    post:
      summary: Wait
      description: ４人集まるのを待つ（ポーリング）。APIの結果でゲーム開始がわかる
      operationId: wait_room_wait_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RoomID"
        required: true
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RoomWaitResponse"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
      security:
        - HTTPBearer: []
  /room/start:
    post:
      summary: Start
      description: ルームのライブ開始リクエスト。部屋のオーナーが叩く
      operationId: start_room_start_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RoomID"
        required: true
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
      security:
        - HTTPBearer: []
  /room/end:
    post:
      summary: End
      description: ルームのライブ終了時リクエスト。ゲーム終わったら各人が叩く
      operationId: end_room_end_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RoomEndRequest"
        required: true
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
      security:
        - HTTPBearer: []
  /room/result:
    post:
      summary: Result
      description: ルームのライブ終了後、リザルト遷移チェックのリクエスト。end 叩いたあとにこれをポーリングする
      operationId: result_room_result_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RoomID"
        required: true
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RoomResultResponse"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
  /room/leave:
    post:
      summary: Leave
      operationId: leave_room_leave_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RoomID"
        required: true
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
      security:
        - HTTPBearer: []
components:
  schemas:
    CreateRoomRequest:
      title: CreateRoomRequest
      required:
        - live_id
        - select_difficulty
      type: object
      properties:
        live_id:
          title: Live Id
          type: integer
        select_difficulty:
          $ref: "#/components/schemas/LiveDifficulty"
    Empty:
      title: Empty
      type: object
      properties: {}
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: "#/components/schemas/ValidationError"
    JoinRoomResult:
      title: JoinRoomResult
      enum:
        - 1
        - 2
        - 3
        - 4
      description: ルーム入場の返却結果
    LiveDifficulty:
      title: LiveDifficulty
      enum:
        - 1
        - 2
      type: integer
      description: 難易度
    ResultUser:
      title: ResultUser
      required:
        - user_id
        - judge_count_list
        - score
      type: object
      properties:
        user_id:
          title: User Id
          type: integer
        judge_count_list:
          title: Judge Count List
          type: array
          items:
            type: integer
        score:
          title: Score
          type: integer
    RoomEndRequest:
      title: RoomEndRequest
      required:
        - room_id
        - score
        - judge_count_list
      type: object
      properties:
        room_id:
          title: Room Id
          type: integer
        score:
          title: Score
          type: integer
        judge_count_list:
          title: Judge Count List
          type: array
          items:
            type: integer
    RoomID:
      title: RoomID
      required:
        - room_id
      type: object
      properties:
        room_id:
          title: Room Id
          type: integer
    RoomInfo:
      title: RoomInfo
      required:
        - room_id
        - live_id
        - joined_user_count
        - max_user_count
      type: object
      properties:
        room_id:
          title: Room Id
          type: integer
        live_id:
          title: Live Id
          type: integer
        joined_user_count:
          title: Joined User Count
          type: integer
        max_user_count:
          title: Max User Count
          type: integer
    RoomJoinRequest:
      title: RoomJoinRequest
      required:
        - room_id
        - select_difficulty
      type: object
      properties:
        room_id:
          title: Room Id
          type: integer
        select_difficulty:
          $ref: "#/components/schemas/LiveDifficulty"
    RoomJoinResponse:
      title: RoomJoinResponse
      required:
        - join_room_result
      type: object
      properties:
        join_room_result:
          $ref: "#/components/schemas/JoinRoomResult"
    RoomListRequest:
      title: RoomListRequest
      required:
        - live_id
      type: object
      properties:
        live_id:
          title: Live Id
          type: integer
    RoomListResponse:
      title: RoomListResponse
      required:
        - room_info_list
      type: object
      properties:
        room_info_list:
          title: Room Info List
          type: array
          items:
            $ref: "#/components/schemas/RoomInfo"
    RoomMember:
      title: RoomMember
      required:
        - user_id
        - name
        - leader_card_id
        - select_difficulty
        - is_host
      type: object
      properties:
        user_id:
          title: User Id
          type: integer
        name:
          title: Name
          type: string
        leader_card_id:
          title: Leader Card Id
          type: integer
        select_difficulty:
          $ref: "#/components/schemas/LiveDifficulty"
        is_host:
          title: Is Host
          type: boolean
    RoomResultResponse:
      title: RoomResultResponse
      required:
        - result_user_list
      type: object
      properties:
        result_user_list:
          title: Result User List
          type: array
          items:
            $ref: "#/components/schemas/ResultUser"
    RoomStatus:
      title: RoomStatus
      enum:
        - 1
        - 2
        - 3
      type: integer
      description: ルームの状態
    RoomWaitResponse:
      title: RoomWaitResponse
      required:
        - status
        - room_user_list
      type: object
      properties:
        status:
          $ref: "#/components/schemas/RoomStatus"
        room_user_list:
          title: Room User List
          type: array
          items:
            $ref: "#/components/schemas/RoomMember"
    SafeUser:
      title: SafeUser
      required:
        - id
        - name
        - leader_card_id
      type: object
      properties:
        id:
          title: Id
          type: integer
        name:
          title: Name
          type: string
        leader_card_id:
          title: Leader Card Id
          type: integer
      description: token を含まないUser
    UserCreateRequest:
      title: UserCreateRequest
      required:
        - user_name
        - leader_card_id
      type: object
      properties:
        user_name:
          title: User Name
          type: string
        leader_card_id:
          title: Leader Card Id
          type: integer
    UserCreateResponse:
      title: UserCreateResponse
      required:
        - user_token
      type: object
      properties:
        user_token:
          title: User Token
          type: string
    ValidationError:
      title: ValidationError
      required:
        - loc
        - msg
        - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            type: string
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
