// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service

import (
	"context"
	"github.com/pollenjp/gameserver-go/api/entity"
	"sync"
)

// Ensure, that CreateUserRepositoryMock does implement CreateUserRepository.
// If this is not the case, regenerate this file with moq.
var _ CreateUserRepository = &CreateUserRepositoryMock{}

// CreateUserRepositoryMock is a mock implementation of CreateUserRepository.
//
//	func TestSomethingThatUsesCreateUserRepository(t *testing.T) {
//
//		// make and configure a mocked CreateUserRepository
//		mockedCreateUserRepository := &CreateUserRepositoryMock{
//			CreateUserFunc: func(ctx context.Context, db Execer, u *entity.User) error {
//				panic("mock out the CreateUser method")
//			},
//		}
//
//		// use mockedCreateUserRepository in code that requires CreateUserRepository
//		// and then make assertions.
//
//	}
type CreateUserRepositoryMock struct {
	// CreateUserFunc mocks the CreateUser method.
	CreateUserFunc func(ctx context.Context, db Execer, u *entity.User) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateUser holds details about calls to the CreateUser method.
		CreateUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Db is the db argument value.
			Db Execer
			// U is the u argument value.
			U *entity.User
		}
	}
	lockCreateUser sync.RWMutex
}

// CreateUser calls CreateUserFunc.
func (mock *CreateUserRepositoryMock) CreateUser(ctx context.Context, db Execer, u *entity.User) error {
	if mock.CreateUserFunc == nil {
		panic("CreateUserRepositoryMock.CreateUserFunc: method is nil but CreateUserRepository.CreateUser was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Db  Execer
		U   *entity.User
	}{
		Ctx: ctx,
		Db:  db,
		U:   u,
	}
	mock.lockCreateUser.Lock()
	mock.calls.CreateUser = append(mock.calls.CreateUser, callInfo)
	mock.lockCreateUser.Unlock()
	return mock.CreateUserFunc(ctx, db, u)
}

// CreateUserCalls gets all the calls that were made to CreateUser.
// Check the length with:
//
//	len(mockedCreateUserRepository.CreateUserCalls())
func (mock *CreateUserRepositoryMock) CreateUserCalls() []struct {
	Ctx context.Context
	Db  Execer
	U   *entity.User
} {
	var calls []struct {
		Ctx context.Context
		Db  Execer
		U   *entity.User
	}
	mock.lockCreateUser.RLock()
	calls = mock.calls.CreateUser
	mock.lockCreateUser.RUnlock()
	return calls
}
