on:
  push:
    branches:
      - "main"
  pull_request:
name: test
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 20s
          --health-timeout 10s
          --health-retries 10
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: webapp
          MYSQL_USER: webapp
          MYSQL_PASSWORD: webapp_no_password
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.20"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          go install github.com/k0kubun/sqldef/cmd/mysqldef@latest
          mysqldef \
            -u webapp \
            -p webapp_no_password \
            -h 127.0.0.1 \
            -P 3306 webapp \
            < ./_tools/mysql/initdb.d/schema.sql
      - run: go test ./... -coverprofile=coverage.out
      - name: report coverage
        uses: k1LoW/octocov-action@v0
